version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine
    restart: always
    networks:
      - net

  backend:
    container_name: django
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DEBUG=0
    volumes:
      - ./core:/app/
      - backend-volume:/vol/web
    networks:
      - net
    depends_on:
      - db
    restart: on-failure


  db:
    container_name: postgresql
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - net

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - backend-volume:/vol/static
    networks:
      - net


volumes:
  postgres-data:
  backend-volume:

networks:
  net:
