version: '3.9'

services:

  backend:
    container_name: django
    build: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000 && \
             python manage.py wait_for_db && \
             python manage.py makemigrations && \
             python manage.py migrate 
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    volumes:
      - ./core:/app/
    depends_on:
      - db
  
  db:
    container_name: postgresql
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: