version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine
    restart: always
    networks:
      - net

  backend:
    container_name: django
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    volumes:
      - backend-volume:/vol/web
    networks:
      - net
    depends_on:
      - db
    restart: on-failure


  db:
    container_name: postgresql
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    networks:
      - net

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - backend-volume:/vol/static
    networks:
      - net


volumes:
  postgres-data:
  backend-volume:

networks:
  net:
