version: '3.9'

services:

  redis:
    image: redis:7.0.11-alpine
    networks:
      - net

  backend:
    container_name: django
    build: .
    ports:
      - 8000:8000
    command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev-db
      - DB_USER=dev-user
      - DB_PASS=changeme
      - SECRET_KEY=test
      - ALLOWED_HOSTS=127.0.0.1 *
      - DEBUG=1
    volumes:
      - ./core:/app/
      - dev-static-data:/vol/web/static
      - dev-media-data:/vol/web/media
    networks:
      - net
    depends_on:
      - db
      - redis
    restart: on-failure
    
  
  db:
    container_name: postgresql
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev-db
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    networks:
      - net
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=80
    restart: always


volumes:
  dev-db-data:
  dev-static-data:
  dev-media-data:

networks:
  net: