# Generated by Django 4.2 on 2024-01-27 12:48

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, validators=[accounts.validators.age_validator]),
        ),
    ]
