# Generated by Django 4.2 on 2024-01-30 06:50

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_img_file_path, validators=[accounts.validators.profile_image_size_validator], verbose_name='profile image'),
        ),
    ]
