# Generated by Django 4.2 on 2024-01-27 12:59

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alley',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='alley'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='entire_address',
            field=models.TextField(blank=True, null=True, verbose_name='entire address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_img_file_path, validators=[accounts.validators.profile_image_size_validator], verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
    ]
