# Generated by Django 4.2 on 2024-01-27 13:00

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_alley_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[accounts.validators.age_validator]),
        ),
    ]
